# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: DashoGames.PiozaGameLauncher
PackageVersion: 0.4.0
InstallerLocale: pl-PL
InstallerType: msi
ProductCode: '{88525005-EC45-4536-A18D-09E99B266E54}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Shieldowskyy/PiozaGameLauncher/releases/download/v.0.4.0/PiozaGL-0.4.0.msi
  InstallerSha256: 6C4C2074E5DF14BE20E876679FA2FCF9DC56410F6743D416C99F2C2E4869B8CF
ManifestType: installer
ManifestVersion: 1.6.0
